### ISSUE TITLE
TC-2 Document Requirements for the first app

### ISSUE THREAD

**Issue by sbandaru-cpal** [sbandaru-cpal/coding-solutions#2]

**Comment by rrayapureddi-cpal** [comment]
Hello

**Comment by vsak-cpal** [comment]
Proposed Requirement:
Design an Android and Iphone compatible mobile application with different categories so that when user wants to spend x amount of money in a category he can determine which state in US would be a cheaper option to save taxes.

Version Releases:

Version 1.0: Basic application to provide user with different Sales Tax categories and a text box to enter amount and display results in Sorted order (Min to Max)) to determine how much the user will be spending depending on Sales tax.

Enhancement Releases:
Version 2.0: 
               1. Determine User location give an approximate distance based sort to let user know how far is the nearest state for to him to spend amount x.
               2. Let user enter a time frame to provide user with notifications and reminders so that user is notified when he is in that area to buy what he has in his wishlist.

Version 3.0: 
              1. Add database connectivity and use internet connection to dynamically determine what item and which state has cheapest and any other offers on the existing item selected.
